### ISSUE TITLE
送付状を作る

### ISSUE THREAD

**Issue by ict-sakata** [ict-inc/rp-01#1]
最初に送付状を作りましょう。

**Comment by ict-tanabe** [comment]
テスト

**Comment by ict-sakata** [comment]
変更した部分を全部記憶しているので、最初の部分でいっぱいアサインがなんとかって書いてあるのは、私がいろいろいじったからです。

**Comment by ict-mikami** [comment]
test

**Comment by ict-sakata** [comment]
うーん、まだよくわからん。
issueには担当者をアサインする。この送付状作成のissueは坂田が担当者になっている。
例えばここで送付状について話し合い、画像をアップしたり、選択したりして、issueの議論が終わったらcloseするんだ。
